language: julia
sudo: true
os:
    - linux
    - osx
julia:
    - 0.7
    # - nightly
addons:
  apt:
    packages:
      - python3-pip
before_install:
    - sudo apt-get update
    - sudo pip install --upgrade visualdl
script:
    - julia -e 'import Pkg; Pkg.build(); Pkg.test(; coverage=true)'
after_success:
    - julia -e 'import Pkg; Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
notifications:
    email: true